name: Close Old Issues
on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  close-issues:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Close Old Issues
        run: |
          open_issues=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/issues?state=open" \
            | jq -r '.[] | .number')
          for issue in $open_issues; do
            # Get the last updated timestamp of the issue
            issue_data=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              "https://api.github.com/repos/${{ github.repository }}/issues/$issue")
            last_updated=$(echo $issue_data | jq -r '.updated_at')
            days_since_update=$(( ( $(date +%s) - $(date -d "$last_updated" +%s) ) / 86400 ))
            
            # Check if the issue has a reminder comment
            reminder_comment=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              "https://api.github.com/repos/${{ github.repository }}/issues/$issue/comments" \
              | jq -r '.[] | select(.body | contains("This issue will be closed in 5 days if no further activity occurs.")) | .created_at')
            
            if [ -z "$reminder_comment" ] && [ $days_since_update -ge 25 ] && [ $days_since_update -lt 30 ]; then
              # Add a reminder comment after 25 days of inactivity
              curl -s -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                -H "Accept: application/vnd.github.v3+json" \
                -d '{"body":"This issue will be closed in 5 days if no further activity occurs."}' \
                "https://api.github.com/repos/${{ github.repository }}/issues/$issue/comments"
            elif [ $days_since_update -ge 30 ]; then
              # Close the issue after 30 days of inactivity
              curl -s -X PATCH -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                -H "Accept: application/vnd.github.v3+json" \
                -d '{"state":"closed"}' \
                "https://api.github.com/repos/${{ github.repository }}/issues/$issue"
              
              # Add a comment explaining the issue has been closed
              curl -s -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                -H "Accept: application/vnd.github.v3+json" \
                -d '{"body":"This issue has been automatically closed because it has been inactive for more than 30 days. If you believe this is still relevant, feel free to reopen it or create a new one. Thank you!"}' \
                "https://api.github.com/repos/${{ github.repository }}/issues/$issue/comments"
            fi
          done
